use super::GlobalError;

pub fn run() -> Result<(), GlobalError> {
    Ok(())
}

#[test]
fn testing_challenge_one_day12() -> Result<(), GlobalError> {
    assert_eq!(31, 31);
    Ok(())
}
#[test]
fn testing_challenge_two_day12() -> Result<(), GlobalError> {
    assert_eq!(1, 1);
    Ok(())
}
