use super::GlobalError;

pub fn run() -> Result<(), GlobalError> {
    Ok(())
}

#[test]
fn testing_challenge_one() -> Result<(), GlobalError> {
    assert_eq!(2, 2);
    Ok(())
}
#[test]
fn testing_challenge_two() -> Result<(), GlobalError> {
    assert_eq!(2, 2);
    Ok(())
}
