use super::GlobalError;

pub fn run() -> Result<(), GlobalError> {
    Ok(())
}

#[test]
fn challenge_day_7_test_one() -> Result<(), GlobalError> {
    
    assert_eq!(5, 5);
    Ok(())
}
#[test]
fn challenge_day_7_test_two() -> Result<(), GlobalError> {
   
    assert_eq!(23, 23);
    Ok(())
}